/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "HGF_Temp.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HGF_Temp_StatusReport, HGF_Temp_StatusReport, 2)


PB_BIND(HGF_Temp_DeviceParamReport, HGF_Temp_DeviceParamReport, 2)


PB_BIND(HGF_Temp_DeviceParamSet, HGF_Temp_DeviceParamSet, AUTO)


PB_BIND(HGF_Temp_DeviceControl, HGF_Temp_DeviceControl, AUTO)


PB_BIND(HGF_Temp_BaseRequest, HGF_Temp_BaseRequest, AUTO)


PB_BIND(HGF_Temp_BaseResponse, HGF_Temp_BaseResponse, AUTO)


PB_BIND(HGF_Temp_BasePush, HGF_Temp_BasePush, AUTO)


PB_BIND(HGF_Temp_DeviceStatus, HGF_Temp_DeviceStatus, AUTO)


PB_BIND(HGF_Temp_PlcStatus, HGF_Temp_PlcStatus, AUTO)


PB_BIND(HGF_Temp_DeviceParam, HGF_Temp_DeviceParam, AUTO)


PB_BIND(HGF_Temp_PlcParam, HGF_Temp_PlcParam, AUTO)


PB_BIND(HGF_Temp_DeviceInfo, HGF_Temp_DeviceInfo, AUTO)


PB_BIND(HGF_Temp_DeviceCtrl, HGF_Temp_DeviceCtrl, AUTO)


PB_BIND(HGF_Temp_PlatCmd, HGF_Temp_PlatCmd, AUTO)






