/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0 */

#ifndef PB_HGF_TEMP_HGF_TEMP_PB_H_INCLUDED
#define PB_HGF_TEMP_HGF_TEMP_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _HGF_Temp_EmCmdId {
    HGF_Temp_EmCmdId_CMD_NONE = 0,
    HGF_Temp_EmCmdId_STATUS_REPORT = 1001,
    HGF_Temp_EmCmdId_PARAM_REPORT = 1002,
    HGF_Temp_EmCmdId_PARAM_CONFIG = 2001,
    HGF_Temp_EmCmdId_DEVICE_CONTROL = 2002
} HGF_Temp_EmCmdId;

typedef enum _HGF_Temp_EmErrorCode {
    HGF_Temp_EmErrorCode_ERR_NONE = 0,
    HGF_Temp_EmErrorCode_CMD_ID = 1,
    HGF_Temp_EmErrorCode_CRC_CHECK = 2,
    HGF_Temp_EmErrorCode_PARSER = 3
} HGF_Temp_EmErrorCode;

typedef enum _HGF_Temp_EmFaultCode {
    HGF_Temp_EmFaultCode_FAULT_NONE = 0,
    HGF_Temp_EmFaultCode_FAULTY = 1,
    HGF_Temp_EmFaultCode_START = 2,
    HGF_Temp_EmFaultCode_HIGH_TEMP = 3,
    HGF_Temp_EmFaultCode_LOW_TEMP = 4,
    HGF_Temp_EmFaultCode_COMMCARDFAULT = 5,
    HGF_Temp_EmFaultCode_OVERCURRENT = 6,
    HGF_Temp_EmFaultCode_SHORT_CIRCUIT = 7
} HGF_Temp_EmFaultCode;

/* Struct definitions */
typedef struct _HGF_Temp_BasePush {
    char DeviceId[32];
    uint32_t Timestamp;
} HGF_Temp_BasePush;

typedef struct _HGF_Temp_BaseRequest {
    char DeviceId[32];
    uint32_t Timestamp;
    bool NeedResp;
} HGF_Temp_BaseRequest;

typedef struct _HGF_Temp_BaseResponse {
    char DeviceId[32];
    uint32_t Timestamp;
    HGF_Temp_EmErrorCode ErrCode;
} HGF_Temp_BaseResponse;

typedef struct _HGF_Temp_DeviceCtrl {
    int32_t open;
} HGF_Temp_DeviceCtrl;

typedef struct _HGF_Temp_DeviceInfo {
    char HwVersion[32];
    char FwVersion[32];
    char BootVersion[32];
    char IMEI[32];
    char SimIMSI[32];
    char SimICCID[32];
} HGF_Temp_DeviceInfo;

typedef struct _HGF_Temp_DeviceParam {
    uint32_t setTargetTemp;
    uint32_t setAlarmTemp;
    uint32_t PigCar_setLeftBackStartTemp;
    uint32_t PigCar_setLeftBackStopTemp;
    uint32_t PigCar_setRightFrontStartTemp;
    uint32_t PigCar_setRightFrontStopTemp;
    uint32_t PigCar_setHotTime;
    uint32_t FeedCar_setLeftBackStartTemp;
    uint32_t FeedCar_setLeftBackStopTemp;
    uint32_t FeedCar_setRightFrontStartTemp;
    uint32_t FeedCar_setRightFrontStopTemp;
    uint32_t FeedCar_setHotTime;
    uint32_t deviceType;
} HGF_Temp_DeviceParam;

typedef struct _HGF_Temp_DeviceStatus {
    uint32_t temp1;
    uint32_t temp2;
    uint32_t temp3;
    uint32_t alarmTemp;
    uint32_t targetTemp;
    uint32_t refTemp;
    uint32_t settingTime;
    uint32_t realHotTimeMin;
    uint32_t hotTimeMin;
    char nowCarNum[32];
    uint32_t warning;
} HGF_Temp_DeviceStatus;

typedef struct _HGF_Temp_PlatCmd {
    bool DevReboot;
    bool FactorySetting;
    char DownloadURL[128];
    bool UploadParam;
    bool UploadState;
} HGF_Temp_PlatCmd;

typedef struct _HGF_Temp_PlcParam {
    int32_t MotorState;
} HGF_Temp_PlcParam;

typedef struct _HGF_Temp_PlcStatus {
    uint32_t Link;
    int32_t run;
} HGF_Temp_PlcStatus;

typedef struct _HGF_Temp_DeviceControl {
    bool has_Base;
    HGF_Temp_BaseRequest Base;
    bool has_DevCtrl;
    HGF_Temp_DeviceCtrl DevCtrl;
    bool has_Cmd;
    HGF_Temp_PlatCmd Cmd;
} HGF_Temp_DeviceControl;

typedef struct _HGF_Temp_DeviceParamReport {
    bool has_Base;
    HGF_Temp_BasePush Base;
    bool has_DevInfo;
    HGF_Temp_DeviceInfo DevInfo;
    bool has_Param;
    HGF_Temp_DeviceParam Param;
} HGF_Temp_DeviceParamReport;

typedef struct _HGF_Temp_DeviceParamSet {
    bool has_Base;
    HGF_Temp_BaseRequest Base;
    bool has_Param;
    HGF_Temp_DeviceParam Param;
} HGF_Temp_DeviceParamSet;

typedef struct _HGF_Temp_StatusReport {
    bool has_Base;
    HGF_Temp_BasePush Base;
    bool has_DevInfo;
    HGF_Temp_DeviceInfo DevInfo;
    bool has_DevStatus;
    HGF_Temp_DeviceStatus DevStatus;
} HGF_Temp_StatusReport;


/* Helper constants for enums */
#define _HGF_Temp_EmCmdId_MIN HGF_Temp_EmCmdId_CMD_NONE
#define _HGF_Temp_EmCmdId_MAX HGF_Temp_EmCmdId_DEVICE_CONTROL
#define _HGF_Temp_EmCmdId_ARRAYSIZE ((HGF_Temp_EmCmdId)(HGF_Temp_EmCmdId_DEVICE_CONTROL+1))

#define _HGF_Temp_EmErrorCode_MIN HGF_Temp_EmErrorCode_ERR_NONE
#define _HGF_Temp_EmErrorCode_MAX HGF_Temp_EmErrorCode_PARSER
#define _HGF_Temp_EmErrorCode_ARRAYSIZE ((HGF_Temp_EmErrorCode)(HGF_Temp_EmErrorCode_PARSER+1))

#define _HGF_Temp_EmFaultCode_MIN HGF_Temp_EmFaultCode_FAULT_NONE
#define _HGF_Temp_EmFaultCode_MAX HGF_Temp_EmFaultCode_SHORT_CIRCUIT
#define _HGF_Temp_EmFaultCode_ARRAYSIZE ((HGF_Temp_EmFaultCode)(HGF_Temp_EmFaultCode_SHORT_CIRCUIT+1))


/* Initializer values for message structs */
#define HGF_Temp_StatusReport_init_default       {false, HGF_Temp_BasePush_init_default, false, HGF_Temp_DeviceInfo_init_default, false, HGF_Temp_DeviceStatus_init_default}
#define HGF_Temp_DeviceParamReport_init_default  {false, HGF_Temp_BasePush_init_default, false, HGF_Temp_DeviceInfo_init_default, false, HGF_Temp_DeviceParam_init_default}
#define HGF_Temp_DeviceParamSet_init_default     {false, HGF_Temp_BaseRequest_init_default, false, HGF_Temp_DeviceParam_init_default}
#define HGF_Temp_DeviceControl_init_default      {false, HGF_Temp_BaseRequest_init_default, false, HGF_Temp_DeviceCtrl_init_default, false, HGF_Temp_PlatCmd_init_default}
#define HGF_Temp_BaseRequest_init_default        {"", 0, 0}
#define HGF_Temp_BaseResponse_init_default       {"", 0, _HGF_Temp_EmErrorCode_MIN}
#define HGF_Temp_BasePush_init_default           {"", 0}
#define HGF_Temp_DeviceStatus_init_default       {0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0}
#define HGF_Temp_PlcStatus_init_default          {0, 0}
#define HGF_Temp_DeviceParam_init_default        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define HGF_Temp_PlcParam_init_default           {0}
#define HGF_Temp_DeviceInfo_init_default         {"", "", "", "", "", ""}
#define HGF_Temp_DeviceCtrl_init_default         {0}
#define HGF_Temp_PlatCmd_init_default            {0, 0, "", 0, 0}
#define HGF_Temp_StatusReport_init_zero          {false, HGF_Temp_BasePush_init_zero, false, HGF_Temp_DeviceInfo_init_zero, false, HGF_Temp_DeviceStatus_init_zero}
#define HGF_Temp_DeviceParamReport_init_zero     {false, HGF_Temp_BasePush_init_zero, false, HGF_Temp_DeviceInfo_init_zero, false, HGF_Temp_DeviceParam_init_zero}
#define HGF_Temp_DeviceParamSet_init_zero        {false, HGF_Temp_BaseRequest_init_zero, false, HGF_Temp_DeviceParam_init_zero}
#define HGF_Temp_DeviceControl_init_zero         {false, HGF_Temp_BaseRequest_init_zero, false, HGF_Temp_DeviceCtrl_init_zero, false, HGF_Temp_PlatCmd_init_zero}
#define HGF_Temp_BaseRequest_init_zero           {"", 0, 0}
#define HGF_Temp_BaseResponse_init_zero          {"", 0, _HGF_Temp_EmErrorCode_MIN}
#define HGF_Temp_BasePush_init_zero              {"", 0}
#define HGF_Temp_DeviceStatus_init_zero          {0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0}
#define HGF_Temp_PlcStatus_init_zero             {0, 0}
#define HGF_Temp_DeviceParam_init_zero           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define HGF_Temp_PlcParam_init_zero              {0}
#define HGF_Temp_DeviceInfo_init_zero            {"", "", "", "", "", ""}
#define HGF_Temp_DeviceCtrl_init_zero            {0}
#define HGF_Temp_PlatCmd_init_zero               {0, 0, "", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define HGF_Temp_BasePush_DeviceId_tag           1
#define HGF_Temp_BasePush_Timestamp_tag          2
#define HGF_Temp_BaseRequest_DeviceId_tag        1
#define HGF_Temp_BaseRequest_Timestamp_tag       2
#define HGF_Temp_BaseRequest_NeedResp_tag        3
#define HGF_Temp_BaseResponse_DeviceId_tag       1
#define HGF_Temp_BaseResponse_Timestamp_tag      2
#define HGF_Temp_BaseResponse_ErrCode_tag        3
#define HGF_Temp_DeviceCtrl_open_tag             1
#define HGF_Temp_DeviceInfo_HwVersion_tag        1
#define HGF_Temp_DeviceInfo_FwVersion_tag        2
#define HGF_Temp_DeviceInfo_BootVersion_tag      3
#define HGF_Temp_DeviceInfo_IMEI_tag             4
#define HGF_Temp_DeviceInfo_SimIMSI_tag          5
#define HGF_Temp_DeviceInfo_SimICCID_tag         6
#define HGF_Temp_DeviceParam_setTargetTemp_tag   1
#define HGF_Temp_DeviceParam_setAlarmTemp_tag    2
#define HGF_Temp_DeviceParam_PigCar_setLeftBackStartTemp_tag 3
#define HGF_Temp_DeviceParam_PigCar_setLeftBackStopTemp_tag 4
#define HGF_Temp_DeviceParam_PigCar_setRightFrontStartTemp_tag 5
#define HGF_Temp_DeviceParam_PigCar_setRightFrontStopTemp_tag 6
#define HGF_Temp_DeviceParam_PigCar_setHotTime_tag 7
#define HGF_Temp_DeviceParam_FeedCar_setLeftBackStartTemp_tag 8
#define HGF_Temp_DeviceParam_FeedCar_setLeftBackStopTemp_tag 9
#define HGF_Temp_DeviceParam_FeedCar_setRightFrontStartTemp_tag 10
#define HGF_Temp_DeviceParam_FeedCar_setRightFrontStopTemp_tag 11
#define HGF_Temp_DeviceParam_FeedCar_setHotTime_tag 12
#define HGF_Temp_DeviceParam_deviceType_tag      13
#define HGF_Temp_DeviceStatus_temp1_tag          1
#define HGF_Temp_DeviceStatus_temp2_tag          2
#define HGF_Temp_DeviceStatus_temp3_tag          3
#define HGF_Temp_DeviceStatus_alarmTemp_tag      4
#define HGF_Temp_DeviceStatus_targetTemp_tag     5
#define HGF_Temp_DeviceStatus_refTemp_tag        6
#define HGF_Temp_DeviceStatus_settingTime_tag    7
#define HGF_Temp_DeviceStatus_realHotTimeMin_tag 8
#define HGF_Temp_DeviceStatus_hotTimeMin_tag     9
#define HGF_Temp_DeviceStatus_nowCarNum_tag      10
#define HGF_Temp_DeviceStatus_warning_tag        11
#define HGF_Temp_PlatCmd_DevReboot_tag           1
#define HGF_Temp_PlatCmd_FactorySetting_tag      2
#define HGF_Temp_PlatCmd_DownloadURL_tag         3
#define HGF_Temp_PlatCmd_UploadParam_tag         4
#define HGF_Temp_PlatCmd_UploadState_tag         5
#define HGF_Temp_PlcParam_MotorState_tag         1
#define HGF_Temp_PlcStatus_Link_tag              1
#define HGF_Temp_PlcStatus_run_tag               2
#define HGF_Temp_DeviceControl_Base_tag          1
#define HGF_Temp_DeviceControl_DevCtrl_tag       2
#define HGF_Temp_DeviceControl_Cmd_tag           3
#define HGF_Temp_DeviceParamReport_Base_tag      1
#define HGF_Temp_DeviceParamReport_DevInfo_tag   2
#define HGF_Temp_DeviceParamReport_Param_tag     3
#define HGF_Temp_DeviceParamSet_Base_tag         1
#define HGF_Temp_DeviceParamSet_Param_tag        2
#define HGF_Temp_StatusReport_Base_tag           1
#define HGF_Temp_StatusReport_DevInfo_tag        2
#define HGF_Temp_StatusReport_DevStatus_tag      3

/* Struct field encoding specification for nanopb */
#define HGF_Temp_StatusReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  Base,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  DevInfo,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  DevStatus,         3)
#define HGF_Temp_StatusReport_CALLBACK NULL
#define HGF_Temp_StatusReport_DEFAULT NULL
#define HGF_Temp_StatusReport_Base_MSGTYPE HGF_Temp_BasePush
#define HGF_Temp_StatusReport_DevInfo_MSGTYPE HGF_Temp_DeviceInfo
#define HGF_Temp_StatusReport_DevStatus_MSGTYPE HGF_Temp_DeviceStatus

#define HGF_Temp_DeviceParamReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  Base,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  DevInfo,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  Param,             3)
#define HGF_Temp_DeviceParamReport_CALLBACK NULL
#define HGF_Temp_DeviceParamReport_DEFAULT NULL
#define HGF_Temp_DeviceParamReport_Base_MSGTYPE HGF_Temp_BasePush
#define HGF_Temp_DeviceParamReport_DevInfo_MSGTYPE HGF_Temp_DeviceInfo
#define HGF_Temp_DeviceParamReport_Param_MSGTYPE HGF_Temp_DeviceParam

#define HGF_Temp_DeviceParamSet_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  Base,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  Param,             2)
#define HGF_Temp_DeviceParamSet_CALLBACK NULL
#define HGF_Temp_DeviceParamSet_DEFAULT NULL
#define HGF_Temp_DeviceParamSet_Base_MSGTYPE HGF_Temp_BaseRequest
#define HGF_Temp_DeviceParamSet_Param_MSGTYPE HGF_Temp_DeviceParam

#define HGF_Temp_DeviceControl_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  Base,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  DevCtrl,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  Cmd,               3)
#define HGF_Temp_DeviceControl_CALLBACK NULL
#define HGF_Temp_DeviceControl_DEFAULT NULL
#define HGF_Temp_DeviceControl_Base_MSGTYPE HGF_Temp_BaseRequest
#define HGF_Temp_DeviceControl_DevCtrl_MSGTYPE HGF_Temp_DeviceCtrl
#define HGF_Temp_DeviceControl_Cmd_MSGTYPE HGF_Temp_PlatCmd

#define HGF_Temp_BaseRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   DeviceId,          1) \
X(a, STATIC,   SINGULAR, UINT32,   Timestamp,         2) \
X(a, STATIC,   SINGULAR, BOOL,     NeedResp,          3)
#define HGF_Temp_BaseRequest_CALLBACK NULL
#define HGF_Temp_BaseRequest_DEFAULT NULL

#define HGF_Temp_BaseResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   DeviceId,          1) \
X(a, STATIC,   SINGULAR, UINT32,   Timestamp,         2) \
X(a, STATIC,   SINGULAR, UENUM,    ErrCode,           3)
#define HGF_Temp_BaseResponse_CALLBACK NULL
#define HGF_Temp_BaseResponse_DEFAULT NULL

#define HGF_Temp_BasePush_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   DeviceId,          1) \
X(a, STATIC,   SINGULAR, UINT32,   Timestamp,         2)
#define HGF_Temp_BasePush_CALLBACK NULL
#define HGF_Temp_BasePush_DEFAULT NULL

#define HGF_Temp_DeviceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   temp1,             1) \
X(a, STATIC,   SINGULAR, UINT32,   temp2,             2) \
X(a, STATIC,   SINGULAR, UINT32,   temp3,             3) \
X(a, STATIC,   SINGULAR, UINT32,   alarmTemp,         4) \
X(a, STATIC,   SINGULAR, UINT32,   targetTemp,        5) \
X(a, STATIC,   SINGULAR, UINT32,   refTemp,           6) \
X(a, STATIC,   SINGULAR, UINT32,   settingTime,       7) \
X(a, STATIC,   SINGULAR, UINT32,   realHotTimeMin,    8) \
X(a, STATIC,   SINGULAR, UINT32,   hotTimeMin,        9) \
X(a, STATIC,   SINGULAR, STRING,   nowCarNum,        10) \
X(a, STATIC,   SINGULAR, UINT32,   warning,          11)
#define HGF_Temp_DeviceStatus_CALLBACK NULL
#define HGF_Temp_DeviceStatus_DEFAULT NULL

#define HGF_Temp_PlcStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Link,              1) \
X(a, STATIC,   SINGULAR, INT32,    run,               2)
#define HGF_Temp_PlcStatus_CALLBACK NULL
#define HGF_Temp_PlcStatus_DEFAULT NULL

#define HGF_Temp_DeviceParam_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   setTargetTemp,     1) \
X(a, STATIC,   SINGULAR, UINT32,   setAlarmTemp,      2) \
X(a, STATIC,   SINGULAR, UINT32,   PigCar_setLeftBackStartTemp,   3) \
X(a, STATIC,   SINGULAR, UINT32,   PigCar_setLeftBackStopTemp,   4) \
X(a, STATIC,   SINGULAR, UINT32,   PigCar_setRightFrontStartTemp,   5) \
X(a, STATIC,   SINGULAR, UINT32,   PigCar_setRightFrontStopTemp,   6) \
X(a, STATIC,   SINGULAR, UINT32,   PigCar_setHotTime,   7) \
X(a, STATIC,   SINGULAR, UINT32,   FeedCar_setLeftBackStartTemp,   8) \
X(a, STATIC,   SINGULAR, UINT32,   FeedCar_setLeftBackStopTemp,   9) \
X(a, STATIC,   SINGULAR, UINT32,   FeedCar_setRightFrontStartTemp,  10) \
X(a, STATIC,   SINGULAR, UINT32,   FeedCar_setRightFrontStopTemp,  11) \
X(a, STATIC,   SINGULAR, UINT32,   FeedCar_setHotTime,  12) \
X(a, STATIC,   SINGULAR, UINT32,   deviceType,       13)
#define HGF_Temp_DeviceParam_CALLBACK NULL
#define HGF_Temp_DeviceParam_DEFAULT NULL

#define HGF_Temp_PlcParam_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    MotorState,        1)
#define HGF_Temp_PlcParam_CALLBACK NULL
#define HGF_Temp_PlcParam_DEFAULT NULL

#define HGF_Temp_DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   HwVersion,         1) \
X(a, STATIC,   SINGULAR, STRING,   FwVersion,         2) \
X(a, STATIC,   SINGULAR, STRING,   BootVersion,       3) \
X(a, STATIC,   SINGULAR, STRING,   IMEI,              4) \
X(a, STATIC,   SINGULAR, STRING,   SimIMSI,           5) \
X(a, STATIC,   SINGULAR, STRING,   SimICCID,          6)
#define HGF_Temp_DeviceInfo_CALLBACK NULL
#define HGF_Temp_DeviceInfo_DEFAULT NULL

#define HGF_Temp_DeviceCtrl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    open,              1)
#define HGF_Temp_DeviceCtrl_CALLBACK NULL
#define HGF_Temp_DeviceCtrl_DEFAULT NULL

#define HGF_Temp_PlatCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     DevReboot,         1) \
X(a, STATIC,   SINGULAR, BOOL,     FactorySetting,    2) \
X(a, STATIC,   SINGULAR, STRING,   DownloadURL,       3) \
X(a, STATIC,   SINGULAR, BOOL,     UploadParam,       4) \
X(a, STATIC,   SINGULAR, BOOL,     UploadState,       5)
#define HGF_Temp_PlatCmd_CALLBACK NULL
#define HGF_Temp_PlatCmd_DEFAULT NULL

extern const pb_msgdesc_t HGF_Temp_StatusReport_msg;
extern const pb_msgdesc_t HGF_Temp_DeviceParamReport_msg;
extern const pb_msgdesc_t HGF_Temp_DeviceParamSet_msg;
extern const pb_msgdesc_t HGF_Temp_DeviceControl_msg;
extern const pb_msgdesc_t HGF_Temp_BaseRequest_msg;
extern const pb_msgdesc_t HGF_Temp_BaseResponse_msg;
extern const pb_msgdesc_t HGF_Temp_BasePush_msg;
extern const pb_msgdesc_t HGF_Temp_DeviceStatus_msg;
extern const pb_msgdesc_t HGF_Temp_PlcStatus_msg;
extern const pb_msgdesc_t HGF_Temp_DeviceParam_msg;
extern const pb_msgdesc_t HGF_Temp_PlcParam_msg;
extern const pb_msgdesc_t HGF_Temp_DeviceInfo_msg;
extern const pb_msgdesc_t HGF_Temp_DeviceCtrl_msg;
extern const pb_msgdesc_t HGF_Temp_PlatCmd_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HGF_Temp_StatusReport_fields &HGF_Temp_StatusReport_msg
#define HGF_Temp_DeviceParamReport_fields &HGF_Temp_DeviceParamReport_msg
#define HGF_Temp_DeviceParamSet_fields &HGF_Temp_DeviceParamSet_msg
#define HGF_Temp_DeviceControl_fields &HGF_Temp_DeviceControl_msg
#define HGF_Temp_BaseRequest_fields &HGF_Temp_BaseRequest_msg
#define HGF_Temp_BaseResponse_fields &HGF_Temp_BaseResponse_msg
#define HGF_Temp_BasePush_fields &HGF_Temp_BasePush_msg
#define HGF_Temp_DeviceStatus_fields &HGF_Temp_DeviceStatus_msg
#define HGF_Temp_PlcStatus_fields &HGF_Temp_PlcStatus_msg
#define HGF_Temp_DeviceParam_fields &HGF_Temp_DeviceParam_msg
#define HGF_Temp_PlcParam_fields &HGF_Temp_PlcParam_msg
#define HGF_Temp_DeviceInfo_fields &HGF_Temp_DeviceInfo_msg
#define HGF_Temp_DeviceCtrl_fields &HGF_Temp_DeviceCtrl_msg
#define HGF_Temp_PlatCmd_fields &HGF_Temp_PlatCmd_msg

/* Maximum encoded size of messages (where known) */
#define HGF_Temp_StatusReport_size               337
#define HGF_Temp_DeviceParamReport_size          322
#define HGF_Temp_DeviceParamSet_size             123
#define HGF_Temp_DeviceControl_size              197
#define HGF_Temp_BaseRequest_size                41
#define HGF_Temp_BaseResponse_size               41
#define HGF_Temp_BasePush_size                   39
#define HGF_Temp_DeviceStatus_size               93
#define HGF_Temp_PlcStatus_size                  17
#define HGF_Temp_DeviceParam_size                78
#define HGF_Temp_PlcParam_size                   11
#define HGF_Temp_DeviceInfo_size                 198
#define HGF_Temp_DeviceCtrl_size                 11
#define HGF_Temp_PlatCmd_size                    138

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
